Backup system with tar
Finished actually writing the system, need to test it at this point.

diff --git a/terminator b/terminator
--- a/terminator
+++ b/terminator
@@ -675,144 +675,121 @@ reset_dumps() {
 	fi
 }
 
-reset_dumps "$local_host_backup_dir/systemdumps" 0
+# Determines if a level 0 backup has been missed
+# param Dir $1 -- backup directory
+# param File $2 -- name of file that is supposed to contain level 0 backup
+# param Date $3 -- date that level 0 backup was supposed to take place
+missed_level0_backup() {
+	# Backup directory
+	local backup_dir="$1"
 
-# # Resets dumps by removing all files in current dump directory so that a new
-# #     level 0 dump can be placed inside
-# # param Dir $1 -- directory where system dumps are stored
-# reset_dumps() {
-# 	local dump_dir="$1"
+	# File containing level 0 backup
+	local level0_backup="$2"
 
-# 	rm -rf "$dump_dir/*"
-# }
+	# most recent backup date that should have occurred
+	local required_backup_date=$(date -d "$3" +"%Y%m%d")
 
-# # Determines if a level 0 backup has been missed
-# # param Dir $1 -- backup directory
-# # param File $2 -- name of file that is supposed to contain level 0 backup
-# # param Date $3 -- date that level 0 backup was supposed to take place
-# missed_level0_backup() {
-# 	# Backup directory
-# 	local backup_dir="$1"
-
-# 	# File containing level 0 backup
-# 	local level0_backup="$2"
-
-# 	# most recent backup date that should have occurred
-# 	local required_backup_date=$(date -d "$3" +"%Y%m%d")
-
-# 	# Check if a level 0 backup exists in the first place
-# 	if [[ "$(ls -A "$backup_dir/$level0_backup")" ]] ; then
-# 		# backup exists, get date (only need first row of ls due to ls on file)
-# 		local known_backup_date="$(date -d "$(ls -lFt --full-time \
-# 			"$backup_dir/$level0_backup" \
-# 			| awk 'FNR == 1 {print $6}')" +"%Y%m%d")"
+	# Check if a level 0 backup exists in the first place
+	if [[ "$(ls -A "$backup_dir/$level0_backup")" ]] ; then
+		# backup exists, get date (only need first row of ls due to ls on file)
+		local known_backup_date="$(date -d "$(ls -lFt --full-time \
+			"$backup_dir/$level0_backup" \
+			| awk 'FNR == 1 {print $6}')" +"%Y%m%d")"
 	
-# 	# No level 0 file exists, assume it was missed
-# 	else
-# 		return 0
-# 	fi
+	# No level 0 file exists, assume it was missed
+	else
+		return 0
+	fi
 
-# 	# If a backup has not occurred at the required time (required time greater
-# 	#     than last known backup time), then backup was missed
-# 	if (( "$required_backup_date" > "$known_backup_date" )) ; then
-# 		return 0
-# 	fi
+	# If a backup has not occurred at the required time (required time greater
+	#     than last known backup time), then backup was missed
+	if (( "$required_backup_date" > "$known_backup_date" )) ; then
+		return 0
+	fi
 
-# 	return 1
-# }
+	return 1
+}
 
-# # Function that actually performs entire system backup using dump
-# # param Int $1 -- number indicating level of backup
-# perform_system_backup() {
-# 	local backup_level="$1"
-# 	local backup_file="$HOSTNAME.systemdump.level_$backup_level.dump"
+# Determines when the previous level 0 backup date should have been based on
+#     system_backup_freq in terminator.conf
+previous_level0_backup_date() {
+	local previous_level0_backup_date
 
-# 	# create system backup directory
-# 	create_backup_dirs "$local_host_backup_dir" "systemdump"
+	# Set date when previous level 0 backup was to occur based on 
+	#     terminator.conf
+	if [[ "$system_backup_freq" == "weekly" ]] ; then
+		previous_level0_backup_date="$(previous_weekly_backup_date)"
 
-# 	# Flush file system buffers (force cached writes onto disk)
-# 	sync
+	elif [[ "$system_backup_freq" == "monthly" ]] ; then
+		previous_level0_backup_date="$(previous_monthly_backup_date)"
 
-# 	# Parameter explanation:
-# 	#     -b64: uses 64 kb blocks which seems to be the most optimal for speed
-# 	#     -a: backup everything until finished
-# 	#     -u: write status to /var/lib/dumpdates after success
-# 	#     -q: abort without warning when failing
-# 	# TODO: change this to root once tested
-# 	dump -"$backup_level" -b64 -aq -f "$local_host_backup_dir/$backup_file" /home/tikenn/Desktop/test | gzip -5 > \
-# 		"$local_host_backup_dir/$backup_file"
+	elif [[ "$system_backup_freq" == "yearly" ]] ; then
+		previous_level0_backup_date="$(previous_yearly_backup_date)"
 
-# 	# If dump was successful, file should exist
-# 	if [[ -f "$local_host_backup_dir/$backup_file" ]] ; then
-# 		# If level 0, we're startin' over
-# 		if [[ "$backup_level" == "0" ]] ; then
-# 			reset_dumps "$local_host_backup_dir/systemdump"
-# 		fi
+	fi
 
-# 		# Move backup file into systemdump folder and overwrite older dumps
-# 		#     of same level
-# 		mv "$local_host_backup_dir/$backup_file" \
-# 			"$local_host_backup_dir/systemdump/$backup_file"
+	echo "$previous_level0_backup_date"
+}
 
-# 		# Log info for user
-# 		echo -n "System Backup Info: performed level " >> "$log_file"
-# 		echo "$backup_level system backup" >> "$log_file"
+# Function that actually performs entire system backup using tar
+perform_system_backup() {
+	local previous_level0_backup_date="$(previous_level0_backup_date)"
+	local backup_level="$(backup_level)"
+	local systemdump_dir
+	local snar_file="$HOSTNAME.systemdump.level_$backup_level.snar"
+	local tar_file="$HOSTNAME.systemdump.level_$backup_level.tar.gz"
 
-# 	# File does not exist, log errors and set up email
-# 	else
-# 		# email settings
-# 		error_flag=1
-# 		email_body+=" - System backup\n"
+	# Create system backup directory
+	create_backup_dirs "$local_host_backup_dir" "systemdump"
+	systemdump_dir="$local_host_backup_dir/systemdump"
 
-# 		# log error
-# 		echo "System Backup Fatal Error: $backup_level unsuccessful" \
-# 			>> "$log_file"
+	# If last level 0 backup was missed, perform a level 0, no questions
+	if missed_level0_backup "$local_host_backup_dir/systemdump" ; then
+		backup_level=0
 
-# 		return 1
-# 	fi
+		echo -n "System Backup Notice: previous level 0 backup missed.  " \
+			>> "$log_file"
+		echo "Attempting to perform level 0 backup . . ." >> "$log_file"
+	fi
 
-# 	return 0
-# }
+	# Create snar file for backup_level being performed from newest snar file
+	# Missed backups (other than level 0, which is accounted for above) are of 
+	#     no consequence as failed backups are deleted
+	if ! [[ "$backup_level" == "0" ]] ; then
+		local newest_snar="$(ls -t "$systemdump_dir/"*.snar \
+			| awk 'FNR == 1 {print $1}')"
+		cp "$newest_snar" "$local_host_backup_dir/$snar_file"
+	fi
 
-# # Schedules system backup level based on calculate $(backup_level) and whether
-# #     a backup was missed or not
-# # param Int $1 -- number indicating level of backup
-# # param Dir $2 -- backup directory
-# # param File $3 -- name of file that is supposed to contain level 0 backup
-# schedule_system_backup() {
-# 	local backup_level="$1"
-# 	local backup_dir="$2"
-# 	local level0_backup="$3"
+	# Perform system backup
+	# Command from:  https://help.ubuntu.com/community/BackupYourSystem/TAR
+	tar cvpzf "$local_host_backup_dir/$tar_file" \
+		--exclude="$local_host_backup_dir/$tar_file" --one-file-system /home/tikenn/Desktop/test \
+		2>> "$log_file"
 
-# 	local previous_level0_backup_date
+	# Backup was successful if no error status of previous command
+	if [[ $? == 0]] ; then
+		# Level 0 backups reset everything back to start
+		if [[ "$backup_level" == "0" ]] ; then
+			reset_dumps "$systemdump_dir"
 
-# 	if [[ "$system_backup_freq" == "weekly" ]] ; then 
-# 		previous_level0_backup_date="$(previous_weekly_backup_date)"
+		# Level 1 backups reset back to after level 0 for cycling
+		elif [[ "$backup_level" == "1" ]] ; then
+			reset_dumps "$systemdump_dir" "0"
 
-# 	# Monthly level 0 system dumps
-# 	elif [[ "$system_backup_freq" == "monthly" ]] ; then
-# 		previous_level0_backup_date="$(previous_monthly_backup_date)"
+		fi
 
-# 	# Yearly level 0 system dumps
-# 	elif [[ "$system_backup_freq" == "yearly" ]] ; then
-# 		previous_level0_backup_date="$(previous_yearly_backup_date)"
-# 	fi
+		mv "$local_host_backup_dir/$snar_file" "$systemdump_dir"
+		mv "$local_host_backup_dir/$tar_file" "$systemdump_dir"
+	
+	# Error during backup, setup email
+	else
+		error_flag=1
+		email_body+=" - System backup\n"
+	fi
+}
 
-# 	# If last level 0 backup was missed, perform a level 0, no questions
-# 	if missed_level0_backup "$backup_dir" "$level0_backup" \
-# 		"$previous_level0_backup_date" ; then
-
-# 		perform_system_backup "0"
-
-# 	# Otherwise, just perform backup at normal schedule
-# 	else
-# 		perform_system_backup "$backup_level"
-# 	fi
-
-# }
-
-# schedule_system_backup "$(backup_level)" "$local_host_backup_dir" \
-# 	"$HOSTNAME.systemdump.level_0.dump.gz"
+perform_system_backup
 
 echo >> "$log_file"
 
